// flow-typed signature: dd98199f72924b3c71f0e4c0c6183bc2
// flow-typed version: <<STUB>>/google-maps-react_v^1.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'google-maps-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'google-maps-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'google-maps-react/dist/components/HeatMap' {
  declare module.exports: any;
}

declare module 'google-maps-react/dist/components/InfoWindow' {
  declare module.exports: any;
}

declare module 'google-maps-react/dist/components/Marker' {
  declare module.exports: any;
}

declare module 'google-maps-react/dist/components/Polygon' {
  declare module.exports: any;
}

declare module 'google-maps-react/dist/GoogleApiComponent' {
  declare module.exports: any;
}

declare module 'google-maps-react/dist/index' {
  declare module.exports: any;
}

declare module 'google-maps-react/dist/lib/cancelablePromise' {
  declare module.exports: any;
}

declare module 'google-maps-react/dist/lib/GoogleApi' {
  declare module.exports: any;
}

declare module 'google-maps-react/dist/lib/ScriptCache' {
  declare module.exports: any;
}

declare module 'google-maps-react/dist/lib/String' {
  declare module.exports: any;
}

declare module 'google-maps-react/dist/lib/windowOrGlobal' {
  declare module.exports: any;
}

declare module 'google-maps-react/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'google-maps-react/dist/components/HeatMap.js' {
  declare module.exports: $Exports<'google-maps-react/dist/components/HeatMap'>;
}
declare module 'google-maps-react/dist/components/InfoWindow.js' {
  declare module.exports: $Exports<'google-maps-react/dist/components/InfoWindow'>;
}
declare module 'google-maps-react/dist/components/Marker.js' {
  declare module.exports: $Exports<'google-maps-react/dist/components/Marker'>;
}
declare module 'google-maps-react/dist/components/Polygon.js' {
  declare module.exports: $Exports<'google-maps-react/dist/components/Polygon'>;
}
declare module 'google-maps-react/dist/GoogleApiComponent.js' {
  declare module.exports: $Exports<'google-maps-react/dist/GoogleApiComponent'>;
}
declare module 'google-maps-react/dist/index.js' {
  declare module.exports: $Exports<'google-maps-react/dist/index'>;
}
declare module 'google-maps-react/dist/lib/cancelablePromise.js' {
  declare module.exports: $Exports<'google-maps-react/dist/lib/cancelablePromise'>;
}
declare module 'google-maps-react/dist/lib/GoogleApi.js' {
  declare module.exports: $Exports<'google-maps-react/dist/lib/GoogleApi'>;
}
declare module 'google-maps-react/dist/lib/ScriptCache.js' {
  declare module.exports: $Exports<'google-maps-react/dist/lib/ScriptCache'>;
}
declare module 'google-maps-react/dist/lib/String.js' {
  declare module.exports: $Exports<'google-maps-react/dist/lib/String'>;
}
declare module 'google-maps-react/dist/lib/windowOrGlobal.js' {
  declare module.exports: $Exports<'google-maps-react/dist/lib/windowOrGlobal'>;
}
declare module 'google-maps-react/index' {
  declare module.exports: $Exports<'google-maps-react'>;
}
declare module 'google-maps-react/index.js' {
  declare module.exports: $Exports<'google-maps-react'>;
}
declare module 'google-maps-react/webpack.config.js' {
  declare module.exports: $Exports<'google-maps-react/webpack.config'>;
}
