// flow-typed signature: 1e4976f48fe29133c43770356832dcce
// flow-typed version: <<STUB>>/react-async-script-loader_v^0.3.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-async-script-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-async-script-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-async-script-loader/karma.conf' {
  declare module.exports: any;
}

declare module 'react-async-script-loader/lib/index' {
  declare module.exports: any;
}

declare module 'react-async-script-loader/lib/utils' {
  declare module.exports: any;
}

declare module 'react-async-script-loader/test/index.spec' {
  declare module.exports: any;
}

declare module 'react-async-script-loader/test/utils.spec' {
  declare module.exports: any;
}

declare module 'react-async-script-loader/tests.webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-async-script-loader/karma.conf.js' {
  declare module.exports: $Exports<'react-async-script-loader/karma.conf'>;
}
declare module 'react-async-script-loader/lib/index.js' {
  declare module.exports: $Exports<'react-async-script-loader/lib/index'>;
}
declare module 'react-async-script-loader/lib/utils.js' {
  declare module.exports: $Exports<'react-async-script-loader/lib/utils'>;
}
declare module 'react-async-script-loader/test/index.spec.js' {
  declare module.exports: $Exports<'react-async-script-loader/test/index.spec'>;
}
declare module 'react-async-script-loader/test/utils.spec.js' {
  declare module.exports: $Exports<'react-async-script-loader/test/utils.spec'>;
}
declare module 'react-async-script-loader/tests.webpack.js' {
  declare module.exports: $Exports<'react-async-script-loader/tests.webpack'>;
}
